class ArticlesController < ApplicationController
  # require authentication for mutating actions
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_article, only: %i[show edit update destroy report]

  # Ensure only the owner can edit or delete
  before_action :ensure_authorized_user, only: %i[edit update destroy]

  def index
    # Only show public articles that aren't archived
    @articles = Article.where(is_public: true).where.not(status: "archived")
  end

  def show
  end

  def new
    # Attach the article to the logged-in user
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    # Ensure sensible defaults when omitted
    @article.reports_count ||= 0
    @article.status ||= "active"

    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # ... standard edit, update, destroy methods generated by scaffold ...

  # Custom action to handle reports
  def report
    # mark that someone flagged this item
    @article.reports_count = @article.reports_count.to_i + 1
    @article.save

    redirect_to articles_path, notice: "Article flagged."
  end

  private

  def load_article
    @article = Article.find(params[:id])
  end

  def article_params
    # Don't forget to permit the image!
    params.require(:article).permit(:title, :body, :is_public, :image)
  end
  
  def ensure_authorized_user
    if @article.user != current_user
      redirect_to articles_path, alert: "Only the author may modify that article."
    end
  end
end